### ISSUE TITLE
Error setup with Woocommerce 6.4.1

### ISSUE THREAD

**Issue by timomedia** [cardpay/woocommerce-plugin#1]
Hello!
I tried setup plugin for Woocommerce 6.4.1 but error: Uncaught Error: Call to a member function get_form_fields() on null in includes/payments/class-wc-unlimint-custom-gateway.php on line 82.
you check it bellow [https://prnt.sc/Z6Q4Sr7mz7VD](url)
How to fix it?

**Comment by kashukov** [comment]
Issue was resolved in 1.0.5.
